spring.application.name=demo-user-api

grpc.server.port=9090

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

app.security.admin.username=${APP_SECURITY_ADMIN_USERNAME}
app.security.admin.password=${APP_SECURITY_ADMIN_PASSWORD}
app.security.user.username=${APP_SECURITY_USER_USERNAME}
app.security.user.password=${APP_SECURITY_USER_PASSWORD}
